---
title: "CST4070 - Comp. 3"
output:
  html_document:
    df_print: paged
---

**Student**:

- Name:
- Surname:
- Student number:
- Campus:

> **Important**.  
>
> Your submission will be mainly evaluated according to your comments and not only according to the submitted code. Keep in mind that a correct code that is not well discussed, well justified and well documented will be badly evaluated.

> **How to export your notebook in PDF**.  
>
> To export your Notebook in PDF you need to perform the following steps: 
>
> - "Preview" your notebook, an HTML file should be generated in your machine.
> - Open the HTML file in your browser. Click *Print*.
> - Change the destination to "*Save to PDF*" and click "*Save*".

## 1. Problem definition

State here your research question.

*Tip*: your research question must be well-defined, consistent, and achievable.

## 2. Data description

Describe here the portion of data you intend to use.  
Describe the format of the data, how many observations and features it contains, describe which kind of features are relevant for your enquiry and why.

*Tip*: put in the shoes of the reader knowing nothing about the data you are using. After reading this section, she needs to have a fair understanding of your dataset.

## 3. Feature engineering and data processing 

Clearly define the required features to answer your research question.  
Every designed feature must be clear and rigorously stated.  
Show how you process your data and transform it into the final format, according to the designed features.  

*Tip*: if you manage timeseries, define your temporal unit of analysis (days, weeks, months, etc).  
Data needs to be properly aggregated according to it.

```{r}
x=iris
summary(x)
```


## 4. Modelling

Introduce here the class of machine learning models you are using to the processed dataset.  
Your machine learning model needs to be fully motivate and appropriate.

*Tip*: focus on the main high-level idea, tiny details such as k-fold cross validation instead of train-test, or tuning are off-topic for this assessment.


## 5. Results

Report your main results here.  
You need to present results in a clear and interesting way for the reader with useful tables and visualisations embedded in the text.  
You need to be concise in showing only the most interesting, unexpected results relevant for your project.  

*Tip*: for each result reported, be critical in interpreting the embedded visualisation and in explaining the relevance of the result.

## 6. Conclusion

Conclude your report by summing up your main objective, the very high-level method adopted, the main results you got, report back whether your objectives have been addressed. Close your report by discussing any limitation of your study and by stressing out its implications.


*Tip*: be critical.